### ISSUE TITLE
"attempt to call a nil value" when i run :Telescope cheat

### ISSUE THREAD

**Issue by ahhshm** [nvim-telescope/telescope-cheat.nvim#10]
Whenever I run `:Telescope cheat` i get the following error. I haven't changed any of the default configurations.
```
E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:184: attempt to call a nil value
stack traceback:
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:184: in function 'run_command'
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:244: in function 'load_command'
        [string ":lua"]:1: in main chunk
```

**Comment by MrSpoony** [comment]
I guess this is the expected behavior if you want to search the cheat.sh run `:Telescope cheat fd`

The first time you run this, it will cache all the values and then you can search the cheat.sh with this command.
