### ISSUE TITLE
Updating to new sqlite API?

### ISSUE THREAD

**Issue by akinsho** [nvim-telescope/telescope-cheat.nvim#3]
Hi @tami5,

I've been looking for a good nvim plugin for `cheat.sh` and this looks like the most promising one since it integrates with nvim/tools I already use, but it no longer runs due to updates to the sqlite plugin (which I'm sure you're aware of) I'm wondering if you plan on updating this plugin or if it's essentially defunct?

No pressure in either case, just wondering if I should take it off my list and look elsewhere, or if you might update it in a bit?

**Comment by tami5** [comment]
Thanks for the heads up @akinsho , I totally forgot to update that one.

**Comment by akinsho** [comment]
@tami5 thanks for the fix, sorry for the dumb follow-up question but didn't want to open a new issue especially if it was just me misunderstanding, but it doesn't look like I can do much querying using the existing `fd` command say for example I wanted information on a python lambda with `cheat.sh` I can do something like `curl cht.sh/python/lambda` but I don't think I can make that sort of query with this plugin, is that right?

**Comment by akinsho** [comment]
Oh 🤦🏿‍♂️ just realised I think I was completely confused about this, this plugin doesn't use/maybe isn't related to https://github.com/chubin/cheat.sh at all 😆

**Comment by Conni2461** [comment]
tami wanted to port all cheat pages with scripts and store them inside a database. Then you end up doing Fetch or update db, i cant remember how he named it and it will generate the up to date database.

In the end you have all cheat sheets in a somewhat small (2mb) database, and can use it offline, super fast.

But he never ended up porting all cheat sheet sources. If i recall correctly.

**Comment by tami5** [comment]
> tami wanted to port all cheat pages with scripts and store them inside a database. Then you end up doing Fetch or update db, i cant remember how he named it and it will generate the up to date database.
> 
> 
> 
> In the end you have all cheat sheets in a somewhat small (2mb) database, and can use it offline, super fast.
> 
> 
> 
> But he never ended up porting all cheat sheet sources. If i recall correctly.

Sadly that's exactly what happened, I haven't seen any activity on the repo after release and like updating sqlite api, I too forgot what was the end goal.

Maybe someday when telescope is accessed through tui, I'd be really interested in incorporating all sources like navi or nvi using autocompletion
